(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* src/routes/index.svelte generated by Svelte v3.12.1 */

const { document: document_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];


const file = "src/routes/index.svelte";

function create_fragment(ctx) {
	var meta, script, t0, section, p0, t1, t2, p1, t3, a0, t4, t5, t6, p2, t7, a1, t8, t9, t10, p3, t11;

	const block = {
		c: function create() {
			meta = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("meta");
			script = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("script");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Hello, I am Luca – a Dutch born developer & digital designer who is\n    passionate about meaningful, ethical, accessible digital experiences that\n    leave a positive impact on people and their environment.");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("During my studies at\n    ");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Design Academy Eindhoven");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n    i've made the decision to operate inbetween design and development. I care\n    about tools that work well, for everyone who interfaces with them. By\n    applying my understanding of design processes I aim to be instrumental in\n    realizing intuitive, high standard, digital experiences.");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("I am currently looking for work opportunities. If I sound like a good fit\n    for your team or you want to discuss a project,\n    ");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("get in touch with me");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n    .");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("References and CV are available upon request.");
			this.h()
		},

		l: function claim(nodes) {
			meta = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "META", { name: true, content: true }, false);
			var meta_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(meta);

			meta_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			script = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SCRIPT", { src: true }, false);
			var script_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(script);

			script_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);

			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "SECTION", { id: true }, false);
			var section_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section);

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section_nodes, "P", {}, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Hello, I am Luca – a Dutch born developer & digital designer who is\n    passionate about meaningful, ethical, accessible digital experiences that\n    leave a positive impact on people and their environment.");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(section_nodes);

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section_nodes, "P", {}, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "During my studies at\n    ");

			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p1_nodes, "A", { href: true }, false);
			var a0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a0);

			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a0_nodes, "Design Academy Eindhoven");
			a0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "\n    i've made the decision to operate inbetween design and development. I care\n    about tools that work well, for everyone who interfaces with them. By\n    applying my understanding of design processes I aim to be instrumental in\n    realizing intuitive, high standard, digital experiences.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(section_nodes);

			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section_nodes, "P", {}, false);
			var p2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p2);

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, "I am currently looking for work opportunities. If I sound like a good fit\n    for your team or you want to discuss a project,\n    ");

			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p2_nodes, "A", { href: true }, false);
			var a1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a1);

			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a1_nodes, "get in touch with me");
			a1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, "\n    .");
			p2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(section_nodes);

			p3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(section_nodes, "P", {}, false);
			var p3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p3);

			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p3_nodes, "References and CV are available upon request.");
			p3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			section_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},

		h: function hydrate() {
			document_1.title = "Luca Claessens";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(meta, "name", "Description");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(meta, "content", "Developer and digital designer, based in Eindhoven.");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(meta, file, 18, 2, 375);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(script, "src", "https://identity.netlify.com/v1/netlify-identity-widget.js");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(script, file, 21, 2, 475);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 26, 2, 600);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a0, "href", "https://www.designacademy.nl/");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a0, file, 33, 4, 863);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 31, 2, 830);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a1, "href", "mailto:lucaclae@gmail.com");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a1, file, 42, 4, 1371);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p2, file, 39, 2, 1233);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p3, file, 45, 2, 1447);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section, "id", "about");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section, file, 25, 0, 577);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document_1.head, meta);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document_1.head, script);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, section, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, a0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a0, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, p2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, a1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a1, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(section, p3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p3, t11);
		},

		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(meta);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(script);

			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(section);
			}
		}
	};
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", { block, id: create_fragment.name, type: "component", source: "", ctx });
	return block;
}

function instance($$self) {
	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(() => {
    if (window.netlifyIdentity) {
      window.netlifyIdentity.on("init", user => {
        if (!user) {
          window.netlifyIdentity.on("login", () => {
            document.location.href = "/admin/";
          });
        }
      });
    }
  });

	$$self.$capture_state = () => {
		return {};
	};

	$$self.$inject_state = $$props => {};

	return {};
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", { component: this, tagName: "Routes", options, id: create_fragment.name });
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztDQUdFLHNEQUFPLENBQUMsTUFBTTtJQUNaLElBQUksTUFBTSxDQUFDLGVBQWUsRUFBRTtNQUMxQixNQUFNLENBQUMsZUFBZSxDQUFDLEVBQUUsQ0FBQyxNQUFNLEVBQUUsSUFBSSxJQUFJO1FBQ3hDLElBQUksQ0FBQyxJQUFJLEVBQUU7VUFDVCxNQUFNLENBQUMsZUFBZSxDQUFDLEVBQUUsQ0FBQyxPQUFPLEVBQUUsTUFBTTtZQUN2QyxRQUFRLENBQUMsUUFBUSxDQUFDLElBQUksR0FBRyxTQUFTLENBQUM7V0FDcEMsQ0FBQyxDQUFDO1NBQ0o7T0FDRixDQUFDLENBQUM7S0FDSjtHQUNGLENBQUMsQ0FBQyIsImZpbGUiOiJkY2IxYmNiYzg5NjQyMmEwNWFkYi9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGltcG9ydCB7IG9uTW91bnQgfSBmcm9tIFwic3ZlbHRlXCI7XG5cbiAgb25Nb3VudCgoKSA9PiB7XG4gICAgaWYgKHdpbmRvdy5uZXRsaWZ5SWRlbnRpdHkpIHtcbiAgICAgIHdpbmRvdy5uZXRsaWZ5SWRlbnRpdHkub24oXCJpbml0XCIsIHVzZXIgPT4ge1xuICAgICAgICBpZiAoIXVzZXIpIHtcbiAgICAgICAgICB3aW5kb3cubmV0bGlmeUlkZW50aXR5Lm9uKFwibG9naW5cIiwgKCkgPT4ge1xuICAgICAgICAgICAgZG9jdW1lbnQubG9jYXRpb24uaHJlZiA9IFwiL2FkbWluL1wiO1xuICAgICAgICAgIH0pO1xuICAgICAgICB9XG4gICAgICB9KTtcbiAgICB9XG4gIH0pO1xuPC9zY3JpcHQ+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPkx1Y2EgQ2xhZXNzZW5zPC90aXRsZT5cbiAgPG1ldGFcbiAgICBuYW1lPVwiRGVzY3JpcHRpb25cIlxuICAgIGNvbnRlbnQ9XCJEZXZlbG9wZXIgYW5kIGRpZ2l0YWwgZGVzaWduZXIsIGJhc2VkIGluIEVpbmRob3Zlbi5cIiAvPlxuICA8c2NyaXB0IHNyYz1cImh0dHBzOi8vaWRlbnRpdHkubmV0bGlmeS5jb20vdjEvbmV0bGlmeS1pZGVudGl0eS13aWRnZXQuanNcIj5cblxuICA8L3NjcmlwdD5cbjwvc3ZlbHRlOmhlYWQ+XG48c2VjdGlvbiBpZD1cImFib3V0XCI+XG4gIDxwPlxuICAgIEhlbGxvLCBJIGFtIEx1Y2EgJm5kYXNoOyBhIER1dGNoIGJvcm4gZGV2ZWxvcGVyICYgZGlnaXRhbCBkZXNpZ25lciB3aG8gaXNcbiAgICBwYXNzaW9uYXRlIGFib3V0IG1lYW5pbmdmdWwsIGV0aGljYWwsIGFjY2Vzc2libGUgZGlnaXRhbCBleHBlcmllbmNlcyB0aGF0XG4gICAgbGVhdmUgYSBwb3NpdGl2ZSBpbXBhY3Qgb24gcGVvcGxlIGFuZCB0aGVpciBlbnZpcm9ubWVudC5cbiAgPC9wPlxuICA8cD5cbiAgICBEdXJpbmcgbXkgc3R1ZGllcyBhdFxuICAgIDxhIGhyZWY9XCJodHRwczovL3d3dy5kZXNpZ25hY2FkZW15Lm5sL1wiPkRlc2lnbiBBY2FkZW15IEVpbmRob3ZlbjwvYT5cbiAgICBpJ3ZlIG1hZGUgdGhlIGRlY2lzaW9uIHRvIG9wZXJhdGUgaW5iZXR3ZWVuIGRlc2lnbiBhbmQgZGV2ZWxvcG1lbnQuIEkgY2FyZVxuICAgIGFib3V0IHRvb2xzIHRoYXQgd29yayB3ZWxsLCBmb3IgZXZlcnlvbmUgd2hvIGludGVyZmFjZXMgd2l0aCB0aGVtLiBCeVxuICAgIGFwcGx5aW5nIG15IHVuZGVyc3RhbmRpbmcgb2YgZGVzaWduIHByb2Nlc3NlcyBJIGFpbSB0byBiZSBpbnN0cnVtZW50YWwgaW5cbiAgICByZWFsaXppbmcgaW50dWl0aXZlLCBoaWdoIHN0YW5kYXJkLCBkaWdpdGFsIGV4cGVyaWVuY2VzLlxuICA8L3A+XG4gIDxwPlxuICAgIEkgYW0gY3VycmVudGx5IGxvb2tpbmcgZm9yIHdvcmsgb3Bwb3J0dW5pdGllcy4gSWYgSSBzb3VuZCBsaWtlIGEgZ29vZCBmaXRcbiAgICBmb3IgeW91ciB0ZWFtIG9yIHlvdSB3YW50IHRvIGRpc2N1c3MgYSBwcm9qZWN0LFxuICAgIDxhIGhyZWY9XCJtYWlsdG86bHVjYWNsYWVAZ21haWwuY29tXCI+Z2V0IGluIHRvdWNoIHdpdGggbWU8L2E+XG4gICAgLlxuICA8L3A+XG4gIDxwPlJlZmVyZW5jZXMgYW5kIENWIGFyZSBhdmFpbGFibGUgdXBvbiByZXF1ZXN0LjwvcD5cbjwvc2VjdGlvbj5cbiJdLCJzb3VyY2VSb290IjoiIn0=