backend: 
  branch: master
  name: git-gateway
collections: 
  - 
    create: true
    fields: 
      - 
        default: blog
        label: Layout
        name: layout
        widget: hidden
      - 
        label: Title
        name: title
        widget: string
      - 
        label: "Publish Date"
        name: date
        widget: datetime
      - 
        label: Body
        name: body
        widget: markdown
    folder: static/_posts
    label: Projects
    name: projects
    slug: "{{slug}}"
media_folder: static/uploads
public_folder: /uploads
publish_mode: editorial_workflow
