name: Deploy to Preview Channel

on:
  push:
    branches:
      - preview
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - name: Install JS dependencies
        run: npm install
      - name: Export static bundle
        run: npm run export
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 7d
          projectId: lucaclaessens-32287
          channelId: preview
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
